name: Golang CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-get-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
          
      - name: Download modules
        run: go mod download

      - name: Build binary
        run: go build -v -o app .

      - name: Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: app

  run-tests-linux:
    runs-on: ubuntu-latest
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
          
      - name: Run tests
        run: go test -v ./...

  run-tests-macos:
    runs-on: macos-14
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test -v ./...

  run-tests-windows:
    runs-on: windows-latest
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: run-tests-linux
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-binary

      - name: Make binary executable
        run: chmod +x app

      - name: Copy binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "app"
          target: ${{ secrets.APP_DIR }}
