name: Golang CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-get-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
          
      - name: Download modules
        run: go mod download

      - name: Build binary
        run: go build -v -o app .

      - name: Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: app

  run-tests-linux:
    runs-on: ubuntu-latest
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
          
      - name: Run tests
        run: go test -v ./...

  run-tests-macos-intel:
    runs-on: macos-15-intel
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test -v ./...

  run-tests-macos-silicon:
    runs-on: macos-14
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test -v ./...

  run-tests-windows:
    runs-on: windows-latest
    needs: build-and-get-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: run-tests-windows
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build binary for deploy
        run: |
          mkdir public
          go build -o public/app

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

